# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Node CI

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install

    - name: Test Tap
      run: |
        npm run test:tap

    - name: Test Jest
      run: |
        npm run test:jest

    # How to run only for Node 16+?
    # - name: Test node-fetch
    #   run: |
    #     npm run test:node-fetch

    - name: Test Types
      run: |
        npm run test:typescript

    - name: Coverage
      run: |
        npm run coverage:ci

    - name: Coverage Report
      uses: codecov/codecov-action@v1
